### ISSUE TITLE
[error] create instance

### ISSUE THREAD

**Issue by X52p** [liblava/liblava#20] opened 2020-03-21 17:43 UTC
Linux (Arch)
When trying to run any example or the template I get the following terminal output:

[2020-03-21 18:35:03.200] [lava] [info] >>> 2020 preview / 0.5.0 - lava triangle / 0.5.0 - Mar 21 2020 18:06:29
[2020-03-21 18:35:03.201] [lava] [info] cmd ./lava-triangle
[2020-03-21 18:35:03.201] [lava] [debug] glfw 3.4.0 X11 GLX EGL OSMesa clock_gettime evdev
[2020-03-21 18:35:03.282] [lava] [info] vulkan 1.2.133
[2020-03-21 18:35:03.283] [lava] [error] create instance param
[2020-03-21 18:35:03.283] [lava] [error] create instance

Am I missing dependencies or how do I get a more verbos output?

**Comment by TheLavaBlock** [comment] 2020-03-21 17:54
Have you installed [Vulkan SDK](https://vulkan.lunarg.com/) ? 

I suspect that validation layers are missing when you start the app in debug.

**Comment by X52p** [comment] 2020-03-22 12:25
Thanks for the hint! I made an error setting up the environment variables.
Because I'm using Fish shell, the automatic setup doesn't seam to work.

In case anyone else has this problem, I added the following commands to my config.fish

set -x VULKAN_SDK ~/vulkan/1.2.131.2/x86_64
set -x PATH $VULKAN_SDK/bin $PATH
set -x LD_LIBRARY_PATH $VULKAN_SDK/lib $LD_LIBRARY_PATH
set -x VK_LAYER_PATH $VULKAN_SDK/etc/vulkan/explicit_layer.d

Everything is launching now, but I still have a problem:
After a view seconds of running the application crashes with the following massage:

validation report: Attempt to reset command pool with VkCommandBuffer 0xbb3e359e620[] which is in use. The Vulkan spec states: All VkCommandBuffer objects allocated from commandPool must not be in the pending state (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-vkResetCommandPool-commandPool-00040)
lava-triangle: PATH_TO_PROJECT/liblava-demo/liblava/liblava/base/instance.cpp:117: VkBool32 lava::validation_callback(VkDebugUtilsMessageSeverityFlagBitsEXT, VkDebugUtilsMessageTypeFlagsEXT, const VkDebugUtilsMessengerCallbackDataEXT*, void*): Assertion '!"check validation error"' failed.

It still might be some missing environment variables, but I'm not really sure.

**Comment by X52p** [comment] 2020-04-11 15:45
I just did everything from the beginning again using Bash, just to be sure. I get the same error.

I also found this error in the CmakeError.log:

Performing C SOURCE FILE Test CMAKE_HAVE_LIBC_PTHREAD failed with the following output:
Change Dir: /home/kevin/Documents/Projects/libLava/liblava-demo/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/make cmTC_c650f/fast && /usr/bin/make  -f CMakeFiles/cmTC_c650f.dir/build.make CMakeFiles/cmTC_c650f.dir/build
make[1]: Entering directory '/home/kevin/Documents/Projects/libLava/liblava-demo/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_c650f.dir/src.c.o
/usr/bin/cc   -DCMAKE_HAVE_LIBC_PTHREAD   -o CMakeFiles/cmTC_c650f.dir/src.c.o   -c /home/kevin/Documents/Projects/libLava/liblava-demo/build/CMakeFiles/CMakeTmp/src.c
Linking C executable cmTC_c650f
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_c650f.dir/link.txt --verbose=1
/usr/bin/cc  -DCMAKE_HAVE_LIBC_PTHREAD    CMakeFiles/cmTC_c650f.dir/src.c.o  -o cmTC_c650f 
/usr/bin/ld: CMakeFiles/cmTC_c650f.dir/src.c.o: in function `main':
src.c:(.text+0x3e): undefined reference to `pthread_create'
/usr/bin/ld: src.c:(.text+0x4a): undefined reference to `pthread_detach'
/usr/bin/ld: src.c:(.text+0x56): undefined reference to `pthread_cancel'
/usr/bin/ld: src.c:(.text+0x67): undefined reference to `pthread_join'
collect2: error: ld returned 1 exit status
make[1]: *** [CMakeFiles/cmTC_c650f.dir/build.make:107: cmTC_c650f] Error 1
make[1]: Leaving directory '/home/kevin/Documents/Projects/libLava/liblava-demo/build/CMakeFiles/CMakeTmp'
make: *** [Makefile:141: cmTC_c650f/fast] Error 2


Source file was:
#include <pthread.h>

void* test_func(void* data)
{
  return data;
}

int main(void)
{
  pthread_t thread;
  pthread_create(&thread, NULL, test_func, NULL);
  pthread_detach(thread);
  pthread_cancel(thread);
  pthread_join(thread, NULL);
  pthread_atfork(NULL, NULL, NULL);
  pthread_exit(NULL);

  return 0;
}

Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /home/kevin/Documents/Projects/libLava/liblava-demo/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/make cmTC_a0bec/fast && /usr/bin/make  -f CMakeFiles/cmTC_a0bec.dir/build.make CMakeFiles/cmTC_a0bec.dir/build
make[1]: Entering directory '/home/kevin/Documents/Projects/libLava/liblava-demo/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_a0bec.dir/CheckFunctionExists.c.o
/usr/bin/cc   -DCHECK_FUNCTION_EXISTS=pthread_create   -o CMakeFiles/cmTC_a0bec.dir/CheckFunctionExists.c.o   -c /usr/share/cmake-3.17/Modules/CheckFunctionExists.c
Linking C executable cmTC_a0bec
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_a0bec.dir/link.txt --verbose=1
/usr/bin/cc  -DCHECK_FUNCTION_EXISTS=pthread_create    CMakeFiles/cmTC_a0bec.dir/CheckFunctionExists.c.o  -o cmTC_a0bec  -lpthreads 
/usr/bin/ld: cannot find -lpthreads
collect2: error: ld returned 1 exit status
make[1]: *** [CMakeFiles/cmTC_a0bec.dir/build.make:107: cmTC_a0bec] Error 1
make[1]: Leaving directory '/home/kevin/Documents/Projects/libLava/liblava-demo/build/CMakeFiles/CMakeTmp'
make: *** [Makefile:141: cmTC_a0bec/fast] Error 2

**Comment by TheLavaBlock** [comment] 2020-04-20 07:51
That's strange. I will try to reproduce it on latest Ubuntu 20.04 that will be released on April 23rd.

Travis CI has no problems. I think you've probably already looked in [there](https://github.com/liblava/liblava/blob/master/.travis.yml), right?

**Comment by underdoeg** [comment] 2020-06-09 15:53
I am also on latest arch and don't have any of your issues. I am using the system Vulkan packages for Nvidia though and did not download the sdk separately.

**Comment by underdoeg** [comment] 2020-06-09 18:32
I stand corrected. Seems to be a driver or implementation issue. On my other computer with AMD and radeon driver, I also get

```
[2020-06-09 20:30:27.862] [lava] [error] Validation Error: [ VUID-vkResetCommandPool-commandPool-00040 ] Object 0: handle = 0x5562ab0e75f0, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0xb53e2331 | Attempt to reset command pool with VkCommandBuffer 0x5562ab0e75f0[] which is in use. The Vulkan spec states: All VkCommandBuffer objects allocated from commandPool must not be in the pending state (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-vkResetCommandPool-commandPool-00040)
```

**Comment by underdoeg** [comment] 2020-06-09 20:14
Seems to be a synchronization issue. Adding ```device->call().vkDeviceWaitIdle(device->get()); here https://github.com/liblava/liblava/blob/master/liblava/block/block.cpp#L112 fixes the issue for me. But there are smarter ways to solve this. 
I think the only reason I didnt have that problem with nvidia was because the driver enabled vsync and was always ready anyways.

**Comment by underdoeg** [comment] 2020-06-09 21:51
I narrowed the issue further down to the backbuffer count.  
Here queued_frames is 5 on my radeon system. https://github.com/liblava/liblava/blob/d08f551caffbd18e94903f6c5073a15762994161/liblava/frame/renderer.cpp#L17

But the sync mechanism doesnt like that number and I have to set queued_frames back to 2.

After that all the examples seem to work fine with really high framerates. ~1300 FPS or so

**Closed** 2020-07-05 19:56 UTC
Labels: question
