### ISSUE TITLE
IMGUI assert raised in liblava not present in "clean" IMGUI clone

### ISSUE THREAD

**Issue by rudycazabon** [liblava/liblava#33] opened 2020-08-26 17:13 UTC
Greetings all,

I am encountering an assert present within liblava that is not evident in a 'clean' clone from the ocornut github repo.

The assert:  ```imgui_draw.cpp:2111: bool ImFontAtlasBuildWithStbTruetype(ImFontAtlas*): Assertion `font_offset >= 0 && "FontData is incorrect, or FontNo cannot be found."' failed.```

I've tried two approaches here. 

1) within the liblava local clone I have run the git submodule command for IMGUI to ensure that I am on branch "master" and on a tag greater than v1.72b

2) within the ext/ directory I removed the imgui/ directory and did a full clone into the location.

On both counts the assert is raised.  I have tested a separate imgui/ clone and attempt to **force** the assert to show up consistent with how liblava uses imgui/ but it does not.  

Please advise if there is anything else you all might recommend at this stage.

**Comment by TheLavaBlock** [comment] 2020-08-26 19:33
Welcome on board 🖖 

I tried to reproduce your issue with `latest master` but couldn't get that assert you describe.

Interesting approches. I have just updated imgui. So everything should be up-to-date.

Can you provide some information about the environment and settings you use?

**Comment by TheLavaBlock** [comment] 2020-09-27 04:22
I've run into the same problem now and I hope that the fix helps you as much as it helps me.

**Comment by TheLavaBlock** [comment] 2020-10-10 12:24
@rudycazabon If you have time to check this again, I would be very grateful. 🙏

**Comment by TheLavaBlock** [comment] 2020-10-20 15:46
@rudycazabon I close the bug because it seems to be fixed in 0.5.4. If it still occurs, please reopen it. Thanks

**Closed by TheLavaBlock** 2020-10-20 15:46 UTC
Labels: bug
